[toolchain]
anchor_version = "0.32.0"

[workspace]
members = ["programs/stealth-perps"]

[programs.localnet]
stealth_perps = "StLtHpErPs1111111111111111111111111111111111"

[programs.devnet]
stealth_perps = "REPLACE_WITH_YOUR_DEPLOYED_PROGRAM_ID"

[clusters.localnet]
offset = 0

[clusters.devnet]
# Run: arcium cluster-info --cluster devnet
offset = 456

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[circuits]
open_position     = "https://snkekjxagpohoxwnqplm.supabase.co/storage/v1/object/public/arcium-circuits/apply_funding.arcis"
check_liquidation = "https://snkekjxagpohoxwnqplm.supabase.co/storage/v1/object/public/arcium-circuits/check_liquidation.arcis"
calculate_pnl     = "https://snkekjxagpohoxwnqplm.supabase.co/storage/v1/object/public/arcium-circuits/calculate_pnl.arcis"
apply_funding     = "https://snkekjxagpohoxwnqplm.supabase.co/storage/v1/object/public/arcium-circuits/apply_funding.arcis"

